export const SWITCH_THEME = 'SWITCH_THEME';
export const SWITCH_THEME_TO_BLACK = 'SWITCH_THEME_TO_BLACK';
export const SWITCH_THEME_TO_WHITE = 'SWITCH_THEME_TO_WHITE';

export const FETCH_APOD = 'FETCH_APOD';